services:
  postgres:
    image: postgres:16-alpine
    container_name: mercado-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mercado
      POSTGRES_PASSWORD: mercado
      POSTGRES_DB: mercado
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
